apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: attest-bom-scan-prov
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail  
  rules:
    - name: check-attestions
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/jimbugwadia/demo-java-tomcat:*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/JimBugwadia/demo-java-tomcat/.github/workflows/publish.yaml@refs/tags/*"
              issuer: "https://token.actions.githubusercontent.com"
              additionalExtensions:
                githubWorkflowTrigger: push
                githubWorkflowSha: eb9c3120af463000edb5b786e681fcbf9d1656c8
                githubWorkflowName: build-sign-attest
                githubWorkflowRepository: JimBugwadia/demo-java-tomcat


