name: build-sign-attest

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # TODO derive tag from repo
  TAG: v1

jobs:

  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=v1

    - name: Push Docker image
      id: docker-build-push
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: build/libs/service.war
        output_path: provenance.json

    - name: Upload provenance
      uses: actions/upload-artifact@v2
      with:
        name: provenance.json
        path: provenance.json

  scan-image:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
    steps:

    - name: Get Repository
      run: |
        export GITHUB_REPOSITORY=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.2.2
      with: 
        scan-type: 'image'
        image-ref: ${{ env.REPO }}
        format: 'json'
        ignore-unfixed: true
        vuln-type: 'os,library'
        output: trivy-scan.json

    - name: Add scan metadata
      uses: sergeysova/jq-action@v2
      with:
        cmd: cat trivy-scan.json | jq '. + {timestamp:(now|todateiso8601)}' | jq '. + {scanner:"trivy"}' > scan.json

    - name: Upload vulnerability scan report
      uses: actions/upload-artifact@v2
      with:
        name: scan.json
        path: scan.json
        if-no-files-found: error

  generate-sbom:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
    steps:

    - name: Get Repository
      run: |
        export GITHUB_REPOSITORY=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.6.0
      with:
        image: ${{ env.REPO }}
        artifact-name: sbom.json
        format: cyclonedx-json

  sign-image-attestations:
    runs-on: ubuntu-latest
    needs: [build-image, scan-image, generate-sbom]
    permissions:
      contents: read
      packages: write
      id-token: write   # This is the key for OIDC!
    steps:

    - uses: actions/download-artifact@master
      with:
        name: sbom.json
        if-no-files-found: error

    - uses: actions/download-artifact@master
      with:
        name: scan.json
        if-no-files-found: error

    - uses: actions/download-artifact@master
      with:
        name: provenance.json
        if-no-files-found: error

    - name: Install Cosign
      uses: sigstore/cosign-installer@v2.0.0
      with:
        cosign-release: 'v1.5.1'

    # TODO GET DIGEST
    - name: Get Repository
      run: |
        export GITHUB_REPOSITORY=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # TODO SIGN WITH DIGEST

    - name: Sign image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |          
        cosign sign --force \
        -a "repo=${{ github.repository }}" \
        -a "workflow=${{ github.workflow }}" \
        -a "ref=${{ github.sha }}" \
        ${{ env.REPO }}

    - name : Attest SBOM
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign attest --force --predicate sbom.json --type https://cyclonedx.org/BOM/v1  ${{ env.REPO }}

    - name : Attest Vulnerability Scan
      env:
        COSIGN_EXPERIMENTAL: "true"    
      run: cosign attest --force --predicate scan.json --type https://trivy.aquasec.com/scan/v2  ${{ env.REPO }}

    - name : Attest Provenance
      env:
        COSIGN_EXPERIMENTAL: "true"    
      run: cosign attest --force --predicate provenance.json --type https://example.com/provenance/v1  ${{ env.REPO }}

