name: build-sign-attest

on:
  workflow_dispatch: {}
  push:
    tags:        
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo }}@${{ steps.digest.outputs.digest }}
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-java@v3.10.0
      with:
        distribution: temurin
        java-version: 17
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.0

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{raw}}

    - name: Push Docker image
      id: docker-build-push
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Get image digest
      id: digest
      run: echo "digest=$(docker inspect ${{ steps.docker-build-push.outputs.digest }} | jq -r '.[].RepoDigests[0] | split("@") | .[1]')" >> $GITHUB_OUTPUT

    # Replace with latest SLSA Generator
    # See: https://github.com/ianlewis/actions-test/blob/main/.github/workflows/generic-container.yml
    - name: Generate provenance
      uses: slsa-framework/github-actions-demo@v0.1
      with:
        artifact_path: build/libs/service.war
        output_path: provenance.json

    - name: Upload provenance
      uses: actions/upload-artifact@v3.1.2
      with:
        name: provenance.json
        path: provenance.json

    - name: Lowercase repo name
      id: repo
      run: |
        echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Echo outputs
      run: |
        echo "tags: ${{ steps.meta.outputs.tags }}"
        echo "digest: ${{ steps.digest.outputs.digest }}"
        echo "image: ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo }}@${{ steps.digest.outputs.digest }}"

  scan-image:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
    steps:

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.9.1
      with: 
        scan-type: 'image'
        image-ref: ${{ needs.build-image.outputs.image }}
        format: 'cosign-vuln'
        ignore-unfixed: true
        vuln-type: 'os,library'
        output: scan.json

    - name: Upload vulnerability scan report
      uses: actions/upload-artifact@v2
      with:
        name: scan.json
        path: scan.json
        if-no-files-found: error

  generate-sbom:
    runs-on: ubuntu-latest
    needs: [build-image]
    permissions:
      contents: read
    steps:

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.13.3
      with:
        image:  ${{ needs.build-image.outputs.image }}
        artifact-name: sbom.json
        format: cyclonedx-json

  create-attestations:
    runs-on: ubuntu-latest
    needs: [build-image, scan-image, generate-sbom]
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write   # This is the key for OIDC!
    steps:

    - uses: actions/download-artifact@master
      with:
        name: sbom.json

    - uses: actions/download-artifact@master
      with:
        name: scan.json

    - uses: actions/download-artifact@master
      with:
        name: provenance.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@ced07f21fb1da67979f539bbc6304c16c0677e76 # v2.7.0
      with:
        cosign-release: v1.12.1

    - name: Log in to GHCR
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Sign image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |          
        cosign sign --force \
        -a "repo=${{ github.repository }}" \
        -a "workflow=${{ github.workflow }}" \
        -a "ref=${{ github.sha }}" \
         ${{ needs.build-image.outputs.image }}

    - name : Attest SBOM
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign attest --predicate sbom.json --type https://cyclonedx.org/BOM/v1   ${{ needs.build-image.outputs.image }}

    - name : Attest Vulnerability Scan
      env:
        COSIGN_EXPERIMENTAL: "true"    
      run: cosign attest --replace --predicate scan.json --type https://trivy.aquasec.com/scan/v2   ${{ needs.build-image.outputs.image }}

    - name : Attest Provenance
      env:
        COSIGN_EXPERIMENTAL: "true"    
      run: cosign attest --replace --predicate provenance.json --type https://example.com/provenance/v1  ${{ needs.build-image.outputs.image }}

